title: Graham Bonomo-Jackson
description: Latent Extraction Systems for Model Repair, Dynamic Forecasting, and Uncertainty-Aware Learning

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

url: "https://Gramathon.github.io"
baseurl: ""

github_username: Gramathon
linkedin_url: https://www.linkedin.com/in/graham-bonomo-jackson/